//It is for creating userOrders:
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

//It is for getting userOrders:
export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";

//IT IS TO GET  A DETAILS OF SINGLE ORDER BY ID/DETAILS
export const ORDER_DETALIS_REQUEST = "ORDER_DETALIS_REQUEST";
export const ORDER_DETALIS_SUCCESS = "ORDER_DETALIS_SUCCESS";
export const ORDER_DETALIS_FAIL = "ORDER_DETALIS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
